### ISSUE TITLE
data in the google drive contains only weights, but not models

### ISSUE THREAD

**Issue by linzi-h** [sklcg/shlight#1]
data in the google drive contains only weights, but not models.

**Comment by linzi-h** [comment]
data in the google drive contains only weights, but not data or models

**Comment by linzi-h** [comment]
and, predict.py reports some errors:
line 4: import nets # there is not nets.py
line 8: from common import NetClass # 'NetClass' doesn' t appear in common.py
line 37:Net = Net_cls[tags[0]] # Net_cls didn't appear anywhere else.

**Comment by linzi-h** [comment]
line 8 and line 37 might be corrected as follow:
line 8: from model import NetClass
line 37:Net = NetClass[tags[0]]

**Comment by sklcg** [comment]
Thank you very much for your attention.
Our trained model with the best configuration (alexnet,freeze the weights of backbone network, concat features extracted from two branch, use weight 0.8, 0.2 to balance the SH loss and render loss) has been upload to google driver.

Codes of the current version has fixed bugs mentioned above. You can use it following the README.MD
