### ISSUE TITLE
Hi,could u compress the sh folder in google drive, thank you.

### ISSUE THREAD

**Issue by linzi-h** [sklcg/shlight#2]
this sh folder contains 204800 tiny txt file that is unfriendly for downloading.
I tried to download the files directly ,but the website informed me that was failed to compress and download the sh folder.

**Comment by linzi-h** [comment]
also,the gt folder is empty... @_@

**Comment by sklcg** [comment]
Very good advice. Now we have compressed the folders with many tiny files for friendly downloading.
Ground truth rendering in gt folder has been uploaded.
