### ISSUE TITLE
Hi,the files named "train.txt" and "test.txt" are not uploaded.

### ISSUE THREAD

**Issue by linzi-h** [sklcg/shlight#3]
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from common import model_root, batch_size, epochs, training_examples , testing_examples
  File "D:\experiment\shlight\src\common.py", line 14, in <module>
    with open(os.path.join(data_root,'train.txt')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/rtdata/data_norm/train.txt'

**Comment by sklcg** [comment]
These two files has been uploaded now.
They can also be generated by data/list/select.py.
Also, you can generate other train.txt and test.txt for training other data.
