### ISSUE TITLE
Hi,which tool did u use to render the gt images?

### ISSUE THREAD

**Issue by linzi-h** [sklcg/shlight#6]
![image](https://user-images.githubusercontent.com/18361553/50428882-c795be00-08f5-11e9-9ee4-1edbc771b2df.png)

**Comment by sklcg** [comment]
We implement it ourselves.
You can see the main rendering function in this link:
http://cg.tuoo.me/project/shlight/temporal/render.cpp

**Comment by linzi-h** [comment]
> We implement it ourselves.
> You can see the main rendering function in this link:
> http://cg.tuoo.me/project/shlight/temporal/render.cpp

thanks very much for your kind help!!!!
