### ISSUE TITLE
你好~请问您是怎么生成特定物体的shmap？

### ISSUE THREAD

**Issue by linzi-h** [sklcg/shlight#8]
我自己是先生成了物体在屏幕空间上的法线图：
![front_1](https://user-images.githubusercontent.com/18361553/51086903-19a86180-1787-11e9-8149-67302a6f18b4.jpg)
然后用以下代码将法线转换为shmap：

> def normal2sh(x, y, z):
    # x,y,z为法线的分量
    x2, y2, z2 = x * x, y * y, z * z
    basis = np.zeros(num_coefs_per_channel)
    basis[0] = 1.0 / 2.0 * sqrt(1.0 / pi)
    basis[1] = sqrt(3.0 / (4.0 * pi)) * y
    basis[2] = sqrt(3.0 / (4.0 * pi)) * z
    basis[3] = sqrt(3.0 / (4.0 * pi)) * x
    basis[4] = 1.0 / 2.0 * sqrt(15.0 / pi) * x * y
    basis[5] = 1.0 / 2.0 * sqrt(15.0 / pi) * y * z
    basis[6] = 1.0 / 4.0 * sqrt(5.0 / pi) * (-x * x - y * y + 2 * z * z)
    basis[7] = 1.0 / 2.0 * sqrt(15.0 / pi) * z * x
    basis[8] = 1.0 / 4.0 * sqrt(15.0 / pi) * (x * x - y * y)
    basis[9] = 1.0 / 4.0 * sqrt(35.0 / (2.0 * pi)) * (3 * x2 - y2) * y
    basis[10] = 1.0 / 2.0 * sqrt(105.0 / pi) * x * y * z
    basis[11] = 1.0 / 4.0 * sqrt(21.0 / (2.0 * pi)) * y * (4 * z2 - x2 - y2)
    basis[12] = 1.0 / 4.0 * sqrt(7.0 / pi) * z * (2 * z2 - 3 * x2 - 3 * y2)
    basis[13] = 1.0 / 4.0 * sqrt(21.0 / (2.0 * pi)) * x * (4 * z2 - x2 - y2)
    basis[14] = 1.0 / 4.0 * sqrt(105.0 / pi) * (x2 - y2) * z
    basis[15] = 1.0 / 4.0 * sqrt(35.0 / (2 * pi)) * (x2 - 3 * y2) * x
    return basis[:num_coefs_per_channel]

但是经过这样转换的shmap，产生的图片都过于明亮（用sh\0001\000.txt的sh系数进行渲染）：
![image](https://user-images.githubusercontent.com/18361553/51086928-7015a000-1787-11e9-9f61-3af9f2a6e9e7.png)
而如下的gt\0001\000_horse.jpg，却要柔和好多，请问是您是进行了哪些处理？
![000_horse](https://user-images.githubusercontent.com/18361553/51086941-afdc8780-1787-11e9-8346-1d6098c44d03.jpg)

**Comment by linzi-h** [comment]
我把法线值归一化到[-0.5, 0.5]之间，情况好一些了，但没有你的gt那么好，并且你这个似乎还有自遮蔽的效果。
![image](https://user-images.githubusercontent.com/18361553/51087489-1022f780-178f-11e9-9e42-3bd86e13e52e.png)

**Comment by DearChi** [comment]
上述所列的计算SHMAP的代码看起来是不正确的。此外，gt中图片的渲染没有用到SH，而是直接使用envmap渲染的。
我上传了一份在[Github:google/spherical harmonics](https://github.com/google/spherical-harmonics)基础上用C++实现的一份简易的SH渲染相关的代码[shlight.zip](http://cg.tuoo.me/project/shlight/temporal/shlight.zip) ，核心的渲染过程（envmap渲染，SH渲染，计算光照的SH表示，计算SHMAP等）主要体现在Render.hpp内的几个函数中，你可以查看，编译，运行一下，希望能有所帮助。

**Comment by sklcg** [comment]
上述所列的计算SHMAP的代码看起来是不正确的。此外，gt中图片的渲染没有用到SH，而是直接使用envmap渲染的。
我上传了一份在[Github:google/spherical harmonics](https://github.com/google/spherical-harmonics)基础上用C++实现的一份简易的SH渲染相关的代码[shlight.zip](http://cg.tuoo.me/project/shlight/temporal/shlight.zip) ，核心的渲染过程（envmap渲染，SH渲染，计算光照的SH表示，计算SHMAP等）主要体现在render.hpp内的几个函数中，你可以查看，编译，运行一下，希望能有所帮助。

**Comment by linzi-h** [comment]
能上传这些代码，非常感谢！！！
祝您取得更好的成果！
